language: python
python:
  - "3.6.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls

services:
  - postgresql

before_script:
  - source .travis.sh
  - psql -c 'CREATE DATABASE SEND' -U postgres


# command to run tests
script:
 nosetests --with-coverage --cover-package=app
after_success:
  - coveralls
  - codecov