language: python
python:
  - "3.6.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls

services:
  - postgresql

before_script:
 - psql -c 'create database send_it;' -U postgres
 - export DATABASE_URI="dbname='send_it' host='localhost' port='5432' user='postgres' password=''"
 - export TESTDB_URI="dbname='send_it' host='localhost' port='5432' user='postgres' password=''"
 - export FLASK_ENV=testing


# command to run tests
script:
 nosetests --with-coverage --cover-package=app
after_success:
  - coveralls
  - codecov